sudo: false
language: cpp

addons:
  apt:
    packages:
      - libboost-all-dev
      #- sdcc
      - build-essential
      - g++-arm-linux-gnueabihf
    
env:
  - SDCC=3.3.0

before_install:
  - export SDCC_DIR=/tmp/sdcc-$SDCC
  - chmod +x ./scripts/build-sdcc.sh

install:
  - ./scripts/build-sdcc.sh

before_script:
  - export PATH=$PATH:$SDCC_DIR/bin
  - sdcc --version

script:
  - (cd ./firmware/ver1 && make clean all)
  - (cd ./firmware/ver2 && make clean all)
  - (cd ./tool && make clean all && (cd build_GCC && tar zvcf ubuntu.$TRAVIS_BRANCH.tar.gz *.out) )
  - (cd ./tool && BUILD_DIR=build_GCC_ARM CXX=arm-linux-gnueabihf-g++ make clean all && (cd build_GCC_ARM && tar zvcf raspi.$TRAVIS_BRANCH.tar.gz *.out) )

deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    file: 
      - ./firmware/ver1/build_by_sdcc/NinjaScanLight.hex
      - ./firmware/ver1/build_by_sdcc/NinjaScanLight.omf
      - ./firmware/ver2/build_by_sdcc/NinjaScanLight2.hex
      - ./firmware/ver2/build_by_sdcc/NinjaScanLight2.omf
    skip_cleanup: true
    all_branches: true  # https://github.com/travis-ci/travis-ci/issues/1675
    on:
      tags: true
  - provider: bintray
    user: fenrir-naru
    key:
      secure: $BINTRAY_TOKEN
    file: .travis.bintray.json
    on: master